---
pivotal:
  type: pivotaltracker
  site_url: 'https://www.pivotaltracker.com/'
  token: token

cf_public_jira:
  type: jira
  site_url: 'https://cloudfoundry.atlassian.net'
  username: user
  password: password
